// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWzzSqTzC3gWmKeY7MPrbNpgb-kHoTNBE',
    appId: '1:165039296188:web:6d2a8eab4da7df86fecab9',
    messagingSenderId: '165039296188',
    projectId: 'fir-shopping-list-d4dad',
    authDomain: 'fir-shopping-list-d4dad.firebaseapp.com',
    databaseURL: 'https://fir-shopping-list-d4dad-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-shopping-list-d4dad.appspot.com',
    measurementId: 'G-XR6Z0NV8BS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU95DtFrzJ7mI8XAo6RVO0PU0ghzGxroM',
    appId: '1:165039296188:android:fcd53a7e1021e443fecab9',
    messagingSenderId: '165039296188',
    projectId: 'fir-shopping-list-d4dad',
    databaseURL: 'https://fir-shopping-list-d4dad-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-shopping-list-d4dad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2ZNLnasliiMNp8A72JRl_3XFU2PDm2tg',
    appId: '1:165039296188:ios:5067a9295755397dfecab9',
    messagingSenderId: '165039296188',
    projectId: 'fir-shopping-list-d4dad',
    databaseURL: 'https://fir-shopping-list-d4dad-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-shopping-list-d4dad.appspot.com',
    iosClientId: '165039296188-ngf83p3bcc96i4jcfrkg81dfn6v1u28i.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseShoppingList',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2ZNLnasliiMNp8A72JRl_3XFU2PDm2tg',
    appId: '1:165039296188:ios:717bc5094b380e4cfecab9',
    messagingSenderId: '165039296188',
    projectId: 'fir-shopping-list-d4dad',
    databaseURL: 'https://fir-shopping-list-d4dad-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'fir-shopping-list-d4dad.appspot.com',
    iosClientId: '165039296188-vubqvqjeg5m5oo7s8sifkcjig2s71k2o.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseShoppingList.RunnerTests',
  );
}
